# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-14 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='图书名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
            ],
            options={
                'verbose_name': '图书表',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名称')),
                ('ip', models.CharField(max_length=15, verbose_name='IP地址')),
                ('type', models.IntegerField(choices=[(1, 'web服务器'), (2, '数据库主服务器'), (3, '负载均衡服务器'), (4, '数据库从服务器'), (5, '数据库中间件服务器'), (6, '缓存中间件服务器'), (7, '日志分析服务器')], verbose_name='服务器类型')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '在线')], verbose_name='服务器状态')),
            ],
            options={
                'verbose_name': '服务器主机资源信息管理表',
                'db_table': 'host',
                'ordering': ['-hostname'],
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=50, verbose_name='出版社地址')),
            ],
            options={
                'verbose_name': '出版社表',
                'db_table': 'publish',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Publish'),
        ),
    ]
