# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名称')),
                ('ip', models.CharField(max_length=50, verbose_name='主机的ip')),
                ('type', models.IntegerField(choices=[(1, 'web'), (2, 'mysql master'), (3, 'HA'), (4, 'LB'), (5, 'cache'), (6, 'mycat'), (7, 'mysql slave'), (8, 'hadoop')], verbose_name='主机的服务类型')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '在线')], verbose_name='主机的状态')),
            ],
            options={
                'verbose_name': '主机信息列表',
                'db_table': 'host',
                'ordering': ['-hostname'],
            },
        ),
    ]
