# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table=None,
        ),
    ]
