# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_auto_20190403_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
