# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_host_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
    ]
