# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0004_auto_20190403_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图书名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=100, verbose_name='出版社所在地')),
            ],
            options={
                'db_table': 'publish',
            },
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机信息列表'},
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Publish'),
        ),
    ]
